# Generated by Django 3.2.5 on 2021-07-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('item_name', models.CharField(max_length=50, verbose_name='Item name')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Quantity')),
                ('receive_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Receive quantity')),
                ('receive_by', models.CharField(blank=True, max_length=51, null=True, verbose_name='Receive by')),
                ('received_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Received date')),
                ('issue_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Issue quantity')),
                ('issue_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Issue date')),
                ('issue_by', models.CharField(blank=True, max_length=51, null=True, verbose_name='Issue by')),
                ('phone_no', models.CharField(max_length=51, verbose_name='Phone no')),
                ('bill_no', models.CharField(blank=True, max_length=51, null=True, verbose_name='Bill no')),
                ('export_to_csv', models.BooleanField(default=False)),
            ],
        ),
    ]
