# Generated by Django 3.2.5 on 2021-07-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='phone_no',
            field=models.CharField(max_length=17, verbose_name='Phone no'),
        ),
    ]
