# Generated by Django 3.2.5 on 2021-07-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_alter_stock_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issue_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Issue date'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='received_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Received date'),
        ),
    ]
