# Generated by Django 3.2.5 on 2021-07-28 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0004_stock_issue_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 7, 43, 57, 652401, tzinfo=utc), verbose_name='Issue by'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='received_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Received date'),
        ),
    ]
