# Generated by Django 3.2.5 on 2021-07-28 07:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0005_auto_20210728_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 7, 44, 34, 274995, tzinfo=utc), verbose_name='Issue by'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='received_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 7, 44, 34, 274928, tzinfo=utc), verbose_name='Received date'),
        ),
    ]
