# Generated by Django 3.2.5 on 2021-07-28 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0006_auto_20210728_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 7, 45, 37, 86962, tzinfo=utc), verbose_name='Issue by'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='received_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 7, 45, 37, 86902, tzinfo=utc), verbose_name='Received date'),
        ),
    ]
