# Generated by Django 3.2.5 on 2021-07-28 07:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0007_auto_20210728_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 7, 48, 58, 216132, tzinfo=utc), verbose_name='Issue by'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='received_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 7, 48, 58, 216071, tzinfo=utc), verbose_name='Received date'),
        ),
    ]
