# Generated by Django 3.2.5 on 2021-07-28 07:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0008_auto_20210728_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 7, 50, 7, 56059, tzinfo=utc), verbose_name='Issue date'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='received_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 7, 50, 7, 55998, tzinfo=utc), verbose_name='Received date'),
        ),
    ]
