# Generated by Django 3.2.5 on 2021-07-30 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0009_auto_20210728_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 30, 11, 30, 39, 756124, tzinfo=utc), verbose_name='Issue date'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Item name'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='received_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 30, 11, 30, 39, 756062, tzinfo=utc), verbose_name='Received date'),
        ),
    ]
