# Generated by Django 3.2.5 on 2021-07-31 10:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0010_auto_20210730_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 10, 25, 18, 342525, tzinfo=utc), verbose_name='Issue date'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='phone_no',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Phone no'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='received_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 10, 25, 18, 342442, tzinfo=utc), verbose_name='Received date'),
        ),
    ]
