# Generated by Django 3.2.5 on 2021-07-31 10:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0011_auto_20210731_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 10, 25, 27, 632209, tzinfo=utc), verbose_name='Issue date'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='received_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 10, 25, 27, 632142, tzinfo=utc), verbose_name='Received date'),
        ),
    ]
