# Generated by Django 3.2.5 on 2021-07-31 10:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0012_auto_20210731_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issue_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 31, 10, 27, 32, 476041, tzinfo=utc), null=True, verbose_name='Issue date'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='received_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 31, 10, 27, 32, 475977, tzinfo=utc), null=True, verbose_name='Received date'),
        ),
    ]
